replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/core-workshop/workshop-registry/insurance-frontend
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: yogapriya-cg-ysankar.staging.workshop.cb-sa.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: staging-tls
      hosts:
        - yogapriya-cg-ysankar.staging.workshop.cb-sa.io

backendUrl: https://example.com
fmToken: abcdefg123456789
